[package]
authors = [ "Alex Chan <alex@alexwlchan.net>" ]
edition = "2024"
name = "safari"
version = "2.3.14"

[dependencies]
dirs = "6.0.0"
docopt = "1.1"
plist = "1.7.1"
serde = { version = "1.0.219", features = [ "derive" ] }
tera = "1.20.0"
urlencoding = "2.1.3"
urlparse = "0.7.3"
